name: assignment-test

on:
  push:
    branches:
      - '**'

jobs:
  full-test:
    runs-on: self-hosted
    container:
      image: cuaesd/aesd-autotest:24-assignment5-buildroot
      options: --cpus 8 --memory 8g

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Cache Buildroot downloads
        uses: actions/cache@v3
        with:
          path: |
            buildroot/dl
            buildroot/output/build
          key: buildroot-${{ runner.os }}-${{ hashFiles('**/Config.in') }}

      - name: Run full test
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          echo "Container sees $(nproc) CPUs"
          chmod +x ./full-test.sh
          export MAKEFLAGS="-j$(nproc)"
          ./full-test.sh

      - name: Cleanup SSH agent
        if: always()
        run: ssh-add -D

