name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  full-test:
    runs-on: self-hosted
    container: cuaesd/aesd-autotest:24-assignment5-buildroot

    steps:
      # Checkout your repo with submodules (if any)
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      # Optional: Show submodule status for debugging
      - name: Show git submodule status
        run: git submodule status

      # Run full test script
      - name: Run full test
        run: ./full-test.sh

