name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  full-test:
    runs-on: self-hosted
    container: cuaesd/aesd-autotest:24-assignment5-buildroot

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Cache Buildroot downloads
        uses: actions/cache@v3
        with:
          path: buildroot/dl
          key: buildroot-dl-${{ hashFiles('**/Config.in') }}

      - name: Show system info
        run: |
          echo "CPU Info:"
          lscpu
          echo "Memory:"
          free -h
          echo "Disk Space:"
          df -h
          echo "Available cores: $(nproc)"

      - name: Run full test with parallel build
        run: |
          echo "Starting test at $(date)"
          chmod +x ./full-test.sh
          export MAKEFLAGS="-j$(nproc)"
          ./full-test.sh
          echo "Test completed at $(date)"

