name: assignment-test

on:
  push:
    branches:
      - '**'

jobs:
  basic-check:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Skip build and mark success
        run: |
          echo "Skipping build and tests."
          exit 0
