name: assignment-test

on:
  push:
    branches:
      - '**'  # Triggers the workflow on push to any branch

jobs:
  full-test:
    runs-on: self-hosted  # Ensures the job runs on a self-hosted runner
    container: cuaesd/aesd-autotest:24-assignment5-buildroot  # Specifies the Docker container to use
    timeout-minutes: 120  # Sets a maximum run time for the job

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive  # Initializes and updates submodules

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Loads the SSH private key from GitHub Secrets

      - name: Run full test with parallel build
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"  # Disables strict host key checking for SSH
        run: |
          echo "Starting test at $(date)"
          chmod +x ./full-test.sh
          export MAKEFLAGS="-j$(nproc)"  # Utilizes all available CPU cores for parallel build
          ./full-test.sh
          echo "Test completed at $(date)"

      - name: Cleanup SSH agent
        if: always()
        run: |
          ssh-add -D  # Removes all identities from the SSH agent

